version: "2"
services:
  web:
    build: ./
    image: diffy
    ports:
      - 3000:3000
    volumes:
      - .:/diffy
      - diffy-vol-be:/diffy/backend/node_modules
      - diffy-vol-fe:/diffy/frontend/node_modules
    links:
      - db
    environment:
      - DIFFY_DB_HOST=db
      - DIFFY_WEB_HOST=0.0.0.0
      - DIFFY_GA_ANALYTICS_KEY=none
    stop_signal: SIGINT
  db:
    image: mongo:4.0.13-xenial
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
volumes:
  diffy-vol-be:
  diffy-vol-fe:
